apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-ddb-wo-crac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-ddb-wo-crac
  template:
    metadata:
      labels:
        app: spring-boot-ddb-wo-crac
    spec:
      serviceAccountName: spring-boot-ddb
      containers:
      - name: spring-boot-ddb-wo-crac
        image: SRVC_IMAGE_WO_CRAC
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        command: ["/bin/bash"]
        args: ["/opt/scripts/run-service-wo-crac.sh"]
        env:
        - name: SRVC_JAR_FILE_NAME
          value: CustomerService-0.0.1.jar
        - name: MODE
          valueFrom:
            configMapKeyRef:
              name: spring-demo-config
              key: mode
        - name: AMAZON_DYNAMO_DB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: spring-demo-config
              key: amazon.dynamodb.endpoint