AWSTemplateFormatVersion: "2010-09-09"
Description: CI stack
Parameters:
  CfnS3Bucket:
    Type: String
    Description: Enter the name of the S3 buckets that contains the CloudFormation templates
  ServiceName:
    Type: String
    Description: Enter the service name.
  ServiceJarFilename:
    Type: String
    Description: Enter the service JAR filename.
  CracCheckpointsBucket:
    Type: String
    Description: Enter CRaC checkpoints S3 bucket name
  VpcId:
    Type: String
    Description: Enter the id of the VPC that CI runs in (should have access to EFS where CRaC checkpoint files are stored)
  VpcSubnetIds:
    Type: CommaDelimitedList
    Description: Enter the ids of the subnets that CI runs in (should have access to EFS where CRaC checkpoint files are stored)
  SecurityGroupIds:
    Type: CommaDelimitedList
    Description: Enter the ids of the security group that CI uses for accessing VPC resources (EFS where CRaC checkpoint files are stored) 
  EfsDns:
    Type: String
    Description: Enter the EFS filesystem DNS

Resources:
  CiRole:
    Type: AWS::IAM::Role
    DependsOn: CiStack
    Properties:
      RoleName: !Sub "${ServiceName}-CiRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:role/${ServiceName}-CiCodeBuildRole" 
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ServiceName}-CiRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:*"
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Customer"
                  
  CiStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://${CfnS3Bucket}.s3.${AWS::Region}.amazonaws.com/ci.yaml"
      Parameters:
        ServiceName: !Ref ServiceName
        ServiceJarFilename: !Ref ServiceJarFilename
        CracCheckpointsBucket: !Ref CracCheckpointsBucket
        VpcId: !Ref VpcId
        VpcSubnetIds: !Join [",", !Ref VpcSubnetIds]
        SecurityGroupIds: !Join [",", !Ref SecurityGroupIds]
        EfsDns: !Ref EfsDns
