AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys springdemo infrastructure dependencies and CI pipeline
Parameters:
  CfnS3Bucket:
    Type: String
    Description: Enter the name of the S3 buckets that contains the CloudFormation templates
  ServiceName:
    Type: String
    Description: Enter the service name
  ServiceJarFilename:
    Type: String
    Description: Enter the service JAR filename
  CracCheckpointsBucket:
    Type: String
    Description: Enter CRaC checkpoints S3 bucket name
  VpcId:
    Type: String
    Description: Enter the id of the VPC that CI runs in (should have access to EFS where CRaC checkpoint files are stored)
  VpcSubnetIds:
    Type: CommaDelimitedList
    Description: Enter the ids of the subnets that CI runs in (should have access to EFS where CRaC checkpoint files are stored)
  SecurityGroupIds:
    Type: CommaDelimitedList
    Description: Enter the ids of the security group that CI uses for accessing VPC resources (EFS where CRaC checkpoint files are stored) 
  EfsDns:
    Type: String
    Description: Enter the EFS filesystem DNS

Resources:
  CiStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://${CfnS3Bucket}.s3.${AWS::Region}.amazonaws.com/springdemo-ci.yaml"
      Parameters:
        ServiceName: !Sub "${ServiceName}"
        CfnS3Bucket: !Sub "${CfnS3Bucket}"
        ServiceJarFilename: !Sub "${ServiceJarFilename}"
        CracCheckpointsBucket: !Sub "${CracCheckpointsBucket}"
        VpcId: !Ref VpcId
        VpcSubnetIds: !Join [",", !Ref VpcSubnetIds]
        SecurityGroupIds: !Join [",", !Ref SecurityGroupIds]
        EfsDns: !Ref EfsDns

  InfraStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "https://${CfnS3Bucket}.s3.${AWS::Region}.amazonaws.com/springdemo-infra.yaml"
      Parameters:
        ServiceName: !Sub "${ServiceName}"
        
