apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-crac-efs-mount.yaml
- deployment-crac-s3-cli.yaml
- deployment-crac.yaml
- deployment-nocrac.yaml
- spring-config-map.yaml